var foods = [
    { name: ' Flutter Course',
      price: 200,
      title: "grave your own book",
      img: "https://i.ibb.co/NYVZ1ww/asset-2.png",
    },
    { name: ' HTML AND CSS',
      price: 70,
      title: "ALl in One",
      img: "https://i.ibb.co/YT0z961/asset-3.png",
    },
    { name: ' Javascript',
      price: 1500,
      title: "grave your own book",
      img: 'https://i.ibb.co/B3h6BKs/asset-1.png',
    },
    { name: ' Go lang',
      price: 400,
      title: "grave your own book",
      img: 'https://i.ibb.co/2W8Jf0D/asset-4.png',
    },
    { name: ' Ruby and rails',
      price: 800,
      title: "LIfe gona make it",
      img: 'https://i.ibb.co/NKm10LL/asset-5.png',
    },
    { name: ' Javascript advance',
      price: 250,
      title: "grave your own book",
      img: 'https://i.ibb.co/qpq6ZJz/asset-6.png',
    },
    { name: ' Block chain',
      price: 450,
      title: "Security first",
      img: 'https://i.ibb.co/JrwRpTZ/asset-7.png',
    },
    { name: ' Javascript',
      price: 200,
      title: "grave your own book",
      img: 'https://i.ibb.co/Vj2cwVp/asset-8.png',
    },
    { name: ' Javascript',
      price: 200,
      title: "grave your own book",
      img: 'https://i.ibb.co/CKwc3RS/asset-9.png',
    },
    { name: ' python',
      price: 200,
      title: "grave your osdfgdfok",
      img: 'https://i.ibb.co/9ZTWmfb/asset-10.png',
    },
    { name: ' Javascript',
      price: 200,
      title: "grave your own book",
      img: 'https://i.ibb.co/N631RRV/asset-13.png',
    },
]
export default foods;